steps:
  # Build the container image (no API key needed at build time)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gemini-tedai:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gemini-tedai:latest'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gemini-tedai:$BUILD_ID']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gemini-tedai:latest']
  
  # Deploy container image to Cloud Run with GEMINI_API_KEY from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gemini-tedai'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gemini-tedai:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-secrets'
      - 'GEMINI_API_KEY=GEMINI_API_KEY:latest'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'

images:
  - 'gcr.io/$PROJECT_ID/gemini-tedai:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/gemini-tedai:latest'

options:
  machineType: 'N1_HIGHCPU_8'

